{% set name = "OceanColor" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/OceanColor-{{ version }}.tar.gz
  sha256: c88d7b81ed3e5aef3c754a5fe064c55f37c475e6d55dd405f1d79cb830fa2849

build:
  number: 0
  noarch: python
  entry_points:
    - OceanColor=OceanColor.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.8
  run:
    - aiohttp >=3.8.1
    - click >=8.0
    - fsspec >=2022.1
    - netcdf4 >=1.5.6
    - numpy >=1.21
    - pandas >=1.3
    - pyproj >=3.0
    - python >=3.8
    - requests >=2.27
    - xarray >=0.19

test:
  imports:
    - OceanColor
  commands:
    - pip check
    - OceanColor --help
  requires:
    - pip

about:
  home: https://github.com/castelao/OceanColor
  summary: Deal with NASA Ocean Color data (search and download)
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - castelao
