{% set name = "OceanColor" %}
{% set version = "0.0.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/OceanColor-{{ version }}.tar.gz
  sha256: 919184ba1ad3a709d335ee0b1032ceb648f3a7219947fbc59672c83ca74cb2cd

build:
  number: 0
  noarch: python
  entry_points:
    - OceanColor=OceanColor.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6
  run:
    - click >=7.1.1
    - h5netcdf >=0.8
    - h5py >=2.10
    - netcdf4 >=1.5
    - numpy >=1.17
    - pandas >=1.0
    - pyproj >=2.6
    - python >=3.6
    - requests >=2.23
    - pytables >=3.6
    - xarray >=0.16

test:
  imports:
    - OceanColor
  commands:
    - pip check
    - OceanColor --help
  requires:
    - pip

about:
  home: https://github.com/castelao/OceanColor
  summary: Deal with NASA Ocean Color data (search and download)
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - castelao
